/**
 * Disposable Email Detection
 *
 * Blocks temporary/disposable email addresses to prevent trial abuse.
 * This list is intentionally incomplete - it's a first line of defense,
 * not a complete solution.
 */

// Common disposable email domains (partial list)
// Sources: various public lists of temp email providers
const DISPOSABLE_DOMAINS: Set<string> = new Set([
  // Major disposable providers
  '10minutemail.com',
  '10minutemail.net',
  'guerrillamail.com',
  'guerrillamail.org',
  'guerrillamail.net',
  'guerrillamail.biz',
  'guerrillamail.de',
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'tempmailo.com',
  'tmpmail.org',
  'tmpmail.net',
  'throwaway.email',
  'throwawaymail.com',
  'mailinator.com',
  'mailinator2.com',
  'mailinator.net',
  'maildrop.cc',
  'fakemailgenerator.com',
  'fakeinbox.com',
  'dispostable.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'getairmail.com',
  'getnada.com',
  'nada.email',
  'mailnesia.com',
  'mohmal.com',
  'emailondeck.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.me',
  'sharklasers.com',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamsphere.com',
  'spamherelots.com',
  'mytrashmail.com',
  'mt2009.com',
  'thankyou2010.com',
  'trash2009.com',
  'mt2014.com',
  'tempinbox.com',
  'tempinbox.co.uk',
  'fakeinbox.net',
  'fakeinbox.org',
  'tempr.email',
  'tempsky.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'mintemail.com',
  'mintmail.com',
  'anonymbox.com',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'mailcatch.com',
  'mailscrap.com',
  'mailseal.de',
  'mailslite.com',
  'mailzilla.com',
  'mailzilla.org',
  'mailzilla.orgmbx.cc',
  'mbx.cc',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'migmail.pl',
  'moakt.com',
  'mobi.web.id',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'online.ms',
  'oopi.org',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'privy-mail.com',
  'privymail.de',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyourspamdatabase.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'realtyalerts.ca',
  'recode.me',
  'reconmail.com',
  'recursor.net',
  'regbypass.com',
  'regbypass.comsafe-mail.net',
  'rejectmail.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'sayawaka-dea.info',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharedmailbox.org',
  'shieldemail.com',
  'shiftmail.com',
  'shitmail.me',
  'shortmail.net',
  'shut.name',
  'shut.ws',
  'sibmail.com',
  'sinnlos-mail.de',
  'siteposter.net',
  'slapsfromlastnight.com',
  'slaskpost.se',
  'slopsbox.com',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamsalad.in',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'squizzy.de',
  'ssoia.com',
  'startkeys.com',
  'stinkefinger.net',
  'stop-my-spam.com',
  'streber24.de',
  'streetwisemail.com',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.co.za',
  'tempinbox.com',
  'tempmail.de',
  'tempmail.eu',
  'tempmail.it',
  'tempmail.us',
  'tempmail.ws',
  'tempmail2.com',
  'tempmailaddress.com',
  'tempmaildemo.com',
  'tempmails.net',
  'tempmailservice.com',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thankyou2010.com',
  'thanksnospam.info',
  'thecloudindex.com',
  'thelightning.net',
  'thisisnotmyrealemail.com',
  'throam.com',
  'throwam.com',
  'throwawayemailaddress.com',
  'tilien.com',
  'tittbit.in',
  'tmailinator.com',
  'tmail.ws',
  'tmpjr.me',
  'toiea.com',
  'tokenmail.de',
  'tonymanso.com',
  'toomail.biz',
  'topranklist.de',
  'tormail.net',
  'tormail.org',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2010.com',
  'trash2011.com',
  'trashbox.eu',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'trbvn.com',
  'trialmail.de',
  'trickmail.net',
  'trillianpro.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viralplays.com',
  'vkcode.ru',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'webemail.me',
  'webm4il.info',
  'webuser.in',
  'wegwerf-email-addressen.de',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whopy.com',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wolfsmail.tk',
  'writeme.us',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.co',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yogamaven.com',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.com',
  'zoemail.net',
  'zoemail.org',
  'zomg.info',
  'zxcv.com',
  'zxcvbnm.com',
  'zzz.com',

  // Additional common ones
  'mailnator.com',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'devnullmail.com',
  'dropmail.me',
  'dumpmail.de',
  'e4ward.com',
  'emailage.cf',
  'emailsensei.com',
  'emailthe.net',
  'etranquil.com',
  'etranquil.net',
  'etranquil.org',
  'evopo.com',
  'example.com',
  'explodemail.com',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastkawasaki.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
]);

/**
 * Check if an email domain is a known disposable email provider
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || typeof email !== 'string') {
    return false;
  }

  const domain = email.toLowerCase().split('@')[1];
  if (!domain) {
    return false;
  }

  // Check direct match
  if (DISPOSABLE_DOMAINS.has(domain)) {
    return true;
  }

  // Check if it's a subdomain of a known disposable domain
  // e.g., user@sub.tempmail.com should also be blocked
  const parts = domain.split('.');
  for (let i = 1; i < parts.length; i++) {
    const parentDomain = parts.slice(i).join('.');
    if (DISPOSABLE_DOMAINS.has(parentDomain)) {
      return true;
    }
  }

  return false;
}

/**
 * Validate an email for trial extension
 * Returns an error message if invalid, or null if valid
 */
export function validateTrialEmail(email: string): string | null {
  if (!email || typeof email !== 'string') {
    return 'Email is required';
  }

  const trimmed = email.trim().toLowerCase();

  // Basic format check
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) {
    return 'Invalid email format';
  }

  // Check for disposable email
  if (isDisposableEmail(trimmed)) {
    return 'Temporary email addresses are not allowed';
  }

  return null;
}
